//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCricketStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public int ProductAttrID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AttributeId { get; set; }
        public string Attribute { get; set; }
    
        public virtual Attribute Attribute1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
